-- MySQL Script generated by MySQL Workbench
-- 01/27/16 10:06:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Hueme
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Hueme` ;

-- -----------------------------------------------------
-- Schema Hueme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hueme` DEFAULT CHARACTER SET utf8 ;
USE `Hueme` ;

-- -----------------------------------------------------
-- Table `Hueme`.`mood_colours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hueme`.`mood_colours` ;

CREATE TABLE IF NOT EXISTS `Hueme`.`mood_colours` (
  `id` INT NOT NULL,
  `colour` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hueme`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hueme`.`users` ;

CREATE TABLE IF NOT EXISTS `Hueme`.`users` (
  `id` INT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `photo_url` TINYTEXT NULL,
  `dob` DATE NULL,
  `description` TINYTEXT NULL,
  `gender` VARCHAR(1) NULL,
  `status` TINYTEXT NULL,
  `country` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `zip_code` VARCHAR(10) NULL,
  `access_level` INT NULL,
  `is_active` TINYINT(1) NULL,
  `mood_colours_id` INT NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  PRIMARY KEY (`id`, `mood_colours_id`),
  INDEX `fk_users_mood_colours1_idx` (`mood_colours_id` ASC),
  CONSTRAINT `fk_users_mood_colours`
    FOREIGN KEY (`mood_colours_id`)
    REFERENCES `Hueme`.`mood_colours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Hueme`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hueme`.`posts` ;

CREATE TABLE IF NOT EXISTS `Hueme`.`posts` (
  `id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `content` TINYTEXT NULL,
  `is_active` TINYINT(1) NULL,
  `tags` VARCHAR(50) NULL,
  `isreply` TINYINT(1) NULL,
  `postscol` VARCHAR(45) NULL,
  `mood_colours_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `mood_colours_id`, `users_id`),
  INDEX `fk_posts_mood_colours1_idx` (`mood_colours_id` ASC),
  INDEX `fk_posts_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_posts_mood_colours1`
    FOREIGN KEY (`mood_colours_id`)
    REFERENCES `Hueme`.`mood_colours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Hueme`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '				';


-- -----------------------------------------------------
-- Table `Hueme`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hueme`.`comments` ;

CREATE TABLE IF NOT EXISTS `Hueme`.`comments` (
  `id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `content` TINYTEXT NULL,
  `is_active` TINYINT(1) NULL,
  `posts_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_comments_posts1_idx` (`posts_id` ASC),
  INDEX `fk_comments_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `Hueme`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Hueme`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hueme`.`stat_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hueme`.`stat_history` ;

CREATE TABLE IF NOT EXISTS `Hueme`.`stat_history` (
  `id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYTEXT NULL,
  `users_id` INT NOT NULL,
  `mood_colours_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `mood_colours_id`),
  INDEX `fk_stat_history_users1_idx` (`users_id` ASC),
  INDEX `fk_stat_history_mood_colours1_idx` (`mood_colours_id` ASC),
  CONSTRAINT `fk_stat_history_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Hueme`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stat_history_mood_colours1`
    FOREIGN KEY (`mood_colours_id`)
    REFERENCES `Hueme`.`mood_colours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hueme`.`notify`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hueme`.`notify` ;

CREATE TABLE IF NOT EXISTS `Hueme`.`notify` (
  `id` INT NOT NULL,
  `IsRead` TINYINT(1) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `post_id` INT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_notify_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_notify_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Hueme`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
